### ISSUE TITLE
Ensure liblouis tables directory is writable by process user

### ISSUE THREAD

**Issue by egli** [sbsdev/daisyproducer2#111]
Currently daisyproducer2 runs as root, so this is not an issue. But in the old system the process was run as `www-data` so the tables directory needs to be writable by that user. If we change the user of daisyproducer2 we need to enhance the ansible install scripts to make sure the directory is writable. Something along the lines of the old system:
``` yaml
- name: ensure liblouis tables directory is writable by www-data
  file:
    path: /usr/local/share/liblouis/tables
    state: directory
    owner: root
    group: www-data
    mode: 02775 # new files should have the gid of the root directory
```
